# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b71b76221d20ede0001a2161d6d95fcf53764f6657b7b1e5d1977cbf3c64fab181d7a836a7375ff0993c46343018bc1d242c4c73dc12ad077751d67f26390f4

test:
  secret_key_base: 6fdcc35296ba09c47c2bf6483a2271054ebcc6b176dc0054182c2456966754b8f181c1a3fc058ac4f976ae28c12e3ed0c2ca147d3a83fce94394c18c58557ddd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
